
server.port=${PORT:7717}
server.servlet.context-path=/cbs


spring.datasource.url=${DB_URL}
spring.datasource.username=${USERNAME}
spring.datasource.password=${PASSWORD}



spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


cbs.bank-code=AXB
cbs.account-prefix=2100000000
cbs.customer-prefix=10000005


springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html


logging.level.com.idigiwave.cbs=DEBUG
